site_name: Administración de Sistemas Operativos
site_url: https://example.com/
nav:
  - Home: index.html
  
  - Recordatorio de Commandos:
      - linux: ./recordatorios/commandosLinux.md
      - windows: ./recordatorios/commandosWindows.md
  - UD1-Shell Scripting:
      - Introducción: ./UD1/011_ShellScript_Intro.md
      - Sintaxis: ./UD1/012_ShellScripting_Sintaxis.md
      - Estructuras de Control: ./UD1/013_ShellScripting_Control.md
      - Funciones: ./UD1/014_ShellScripting_VectoresFunciones.md
      
theme:
  name: material
  icon:
    admonition:
      example: octicons/terminal-16
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.integrate
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
