site_name: Administración de Sistemas Operativos
site_url: https://example.com/
nav:
  - Home: index.html
  
  - Recordatorio de Commandos:
      - linux: ./recordatorios/commandosLinux.md
      - windows: ./recordatorios/commandosWindows.md
  - UD1 - Shell Scripting:
      - Introducción: ./UD1/011_ShellScripting_Intro.md
      - Sintaxis: ./UD1/012_ShellScripting_Sintaxis.md
      - Estructuras de Control: ./UD1/013_ShellScripting_Control.md
      - Funciones: ./UD1/014_ShellScripting_VectoresFunciones.md
      
theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:

extra_css:
  - stylesheets/extra.css
